spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
#      globally_quoted_identifiers: 'true'
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\Users\Flavio\Desktop\fileRepositoryFolder