spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: flaviopagano1@gmail.com
    password: dpkypnlhuhswtuol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
